services:
  nginx:
    image: nginx:alpine
    container_name: lab2_nginx
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - lab2_network

  php:
    build: .
    container_name: lab2_php
    volumes:
      - ./www:/var/www/html
    expose:
      - "9000"
    networks:
      - lab2_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  lab2_network:
    driver: bridge
